version: '3'
services:
  mysql:
    image: mysql:5.6.48
    container_name: mysql_server
    environment:
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo123!@#
      MYSQL_ROOT_PASSWORD: root@123.
      MYSQL_DATABASE: laravel_demo
    volumes:
      - ./init-mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3308:3306
    networks:
      extnetwork:
        ipv4_address: 172.19.0.3
  swoole:
    image: wjf295004046/myswoole:v1
    container_name: swoole_server
    restart: always
    volumes:
    - ./init_swoole/swoole_demo:/usr/src/swoole_demo
    ports:
    - 8880:8880
    networks:
      extnetwork:
        ipv4_address: 172.19.0.4
    extra_hosts:
      - "mysql_server: 172.19.0.3"
    command: php /usr/src/swoole_demo/server.php
  php:
    build:
      context: ./init_php
      dockerfile: DockfilePHP
    image: laravel_demo
    container_name: php_server
    restart: always
    ports:
      - 8800:8800
    networks:
      extnetwork:
        ipv4_address: 172.19.0.2
    extra_hosts:
      - "mysql_server: 172.19.0.3"
    volumes:
    - ./init_php/laravel_demo:/usr/src/laravel_demo
networks:
  extnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
